name: Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  windows-job:
    name: Windows test
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean verify

      - name: Show test result (text fallback)
        shell: bash
        run: cat target/surefire-reports/*.txt || echo "No test result found"

      - name: Show test result
        shell: bash
        run: |
          if [ -d target/surefire-reports ]; then
            cat target/surefire-reports/*.txt || echo "Test report exists but no content"
          else
            echo "No test result found"
          fi
